package com.ailudick.capitalismmod.init;

import com.ailudick.capitalismmod.CapitalismMod;
import net.minecraft.core.registries.Registries;
import net.minecraft.network.chat.Component;
import net.minecraft.world.item.CreativeModeTab;
import net.neoforged.neoforge.registries.DeferredHolder;
import net.neoforged.neoforge.registries.DeferredRegister;

public class ModCreativeTabs {
    public static final DeferredRegister<CreativeModeTab> CREATIVE_TABS =
            DeferredRegister.create(Registries.CREATIVE_MODE_TAB, CapitalismMod.MODID);

    public static final DeferredHolder<CreativeModeTab, CreativeModeTab> CAPITALISM_TAB =
            CREATIVE_TABS.register("capitalism_tab", () -> CreativeModeTab.builder()
                    .title(Component.translatable("itemGroup.capitalismmod"))
                    .icon(() -> ModItems.USD_1.get().getDefaultInstance())
                    .displayItems((params, output) -> {
                        output.accept(ModItems.USD_1C.get());
                        output.accept(ModItems.USD_5C.get());
                        output.accept(ModItems.USD_10C.get());
                        output.accept(ModItems.USD_25C.get());
                        output.accept(ModItems.USD_50C.get());
                        output.accept(ModItems.USD_1.get());
                        output.accept(ModItems.USD_2.get());
                        output.accept(ModItems.USD_5.get());
                        output.accept(ModItems.USD_10.get());
                        output.accept(ModItems.USD_20.get());
                        output.accept(ModItems.USD_50.get());
                        output.accept(ModItems.USD_100.get());
                        output.accept(ModItems.CNY_1F.get());
                        output.accept(ModItems.CNY_5F.get());
                        output.accept(ModItems.CNY_1J.get());
                        output.accept(ModItems.CNY_5J.get());
                        output.accept(ModItems.CNY_1.get());
                        output.accept(ModItems.CNY_1_COIN.get());
                        output.accept(ModItems.CNY_5.get());
                        output.accept(ModItems.CNY_10.get());
                        output.accept(ModItems.CNY_20.get());
                        output.accept(ModItems.CNY_50.get());
                        output.accept(ModItems.CNY_100.get());
                        output.accept(ModItems.EUR_1C.get());
                        output.accept(ModItems.EUR_2C.get());
                        output.accept(ModItems.EUR_5C.get());
                        output.accept(ModItems.EUR_10C.get());
                        output.accept(ModItems.EUR_20C.get());
                        output.accept(ModItems.EUR_50C.get());
                        output.accept(ModItems.EUR_1.get());
                        output.accept(ModItems.EUR_2.get());
                        output.accept(ModItems.EUR_5.get());
                        output.accept(ModItems.EUR_10.get());
                        output.accept(ModItems.EUR_20.get());
                        output.accept(ModItems.EUR_50.get());
                        output.accept(ModItems.EUR_100.get());
                        output.accept(ModItems.EUR_200.get());
                        output.accept(ModItems.EUR_500.get());
                        output.accept(ModItems.RUB_1K.get());
                        output.accept(ModItems.RUB_5K.get());
                        output.accept(ModItems.RUB_10K.get());
                        output.accept(ModItems.RUB_50K.get());
                        output.accept(ModItems.RUB_1.get());
                        output.accept(ModItems.RUB_2.get());
                        output.accept(ModItems.RUB_5.get());
                        output.accept(ModItems.RUB_10.get());
                        output.accept(ModItems.RUB_5_NOTE.get());
                        output.accept(ModItems.RUB_10_NOTE.get());
                        output.accept(ModItems.RUB_50.get());
                        output.accept(ModItems.RUB_100.get());
                        output.accept(ModItems.RUB_200.get());
                        output.accept(ModItems.RUB_500.get());
                        output.accept(ModItems.RUB_1000.get());
                        output.accept(ModItems.RUB_2000.get());
                        output.accept(ModItems.RUB_5000.get());
                        output.accept(ModItems.DEBIT_CARD.get());
                        output.accept(ModItems.CREDIT_CARD.get());
                        output.accept(ModItems.BANK.get());
                        output.accept(ModItems.BUSINESS_BUREAU.get());
                        output.accept(ModItems.BUSINESS_LICENSE.get());
                        output.accept(ModItems.INVOICE.get());
                        output.accept(ModItems.DEBUG_STICK.get());
                        output.accept(ModItems.PLACEHOLDER_NPC_SPAWN_EGG.get());
                        output.accept(ModItems.COMMODITY_EXCHANGE.get());
                        output.accept(ModItems.STOCK_EXCHANGE.get());
                        output.accept(ModItems.SECURITIES_COMMISSION.get());
                        output.accept(ModItems.TAX_BUREAU.get());
                        output.accept(ModItems.COMPANY.get());
                        output.accept(ModItems.WAREHOUSE.get());
                        output.accept(ModItems.FUTURES_EXCHANGE.get());
                        output.accept(ModItems.AUCTION_HOUSE.get());
                        output.accept(ModItems.BOND_MARKET.get());
                        output.accept(ModItems.PROCUREMENT.get());
                        output.accept(ModItems.LOGISTICS_CENTER.get());
                        output.accept(ModItems.TRANSFER_STATION.get());
                        output.accept(ModItems.PORT.get());
                        output.accept(ModItems.MAILBOX.get());
                        output.accept(ModItems.INDIVIDUAL_BUSINESS.get());
                        output.accept(ModItems.STEEL_SHEET.get());
                        output.accept(ModItems.COPPER_WIRE.get());
                        output.accept(ModItems.GLASS_LENS.get());
                        output.accept(ModItems.ELECTRIC_LAMP.get());
                        output.accept(ModItems.FLOUR.get());
                        output.accept(ModItems.METAL_CAN.get());
                        output.accept(ModItems.CANNED_FOOD.get());
                        output.accept(ModItems.GREEN_LUMBER.get());
                        output.accept(ModItems.DRIED_LUMBER.get());
                        output.accept(ModItems.WOODEN_CRATE.get());
                        output.accept(ModItems.FURNITURE.get());
                        output.accept(ModItems.CRUDE_OIL.get());
                        output.accept(ModItems.NAPHTHA.get());
                        output.accept(ModItems.FUEL_OIL.get());
                        output.accept(ModItems.BASE_OIL.get());
                        output.accept(ModItems.PLASTIC_PELLETS.get());
                        output.accept(ModItems.POLYETHYLENE_PELLETS.get());
                        output.accept(ModItems.POLYPROPYLENE_PELLETS.get());
                        output.accept(ModItems.SYNTHETIC_RUBBER.get());
                        output.accept(ModItems.ETHYLENE_GLYCOL.get());
                        output.accept(ModItems.EPOXY_RESIN.get());
                        output.accept(ModItems.BENZENE.get());
                        output.accept(ModItems.STYRENE_MONOMER.get());
                        output.accept(ModItems.ABS_RESIN.get());
                        output.accept(ModItems.FAN_BLADES.get());
                        output.accept(ModItems.FAN_CONTROL.get());
                        output.accept(ModItems.POLYSILICON.get());
                        output.accept(ModItems.SILICON_WAFER.get());
                        output.accept(ModItems.SILICON_DIE.get());
                        output.accept(ModItems.TESTED_DIE.get());
                        output.accept(ModItems.LEAD_FRAME.get());
                        output.accept(ModItems.MOLD_COMPOUND.get());
                        output.accept(ModItems.PACKAGED_CHIP.get());
                        output.accept(ModItems.CIRCUIT_BOARD.get());
                        output.accept(ModItems.PCB_SUBSTRATE.get());
                        output.accept(ModItems.DRILLED_PCB_PANEL.get());
                        output.accept(ModItems.ETCHED_PCB.get());
                        output.accept(ModItems.SOLDER_MASKED_PCB.get());
                        output.accept(ModItems.COPPER_FOIL.get());
                        output.accept(ModItems.SOLDER.get());
                        output.accept(ModItems.SMD_COMPONENTS.get());
                        output.accept(ModItems.PASSIVE_COMPONENTS.get());
                        output.accept(ModItems.POWER_MANAGEMENT_IC.get());
                        output.accept(ModItems.DISPLAY_DRIVER.get());
                        output.accept(ModItems.DISPLAY_PANEL.get());
                        output.accept(ModItems.PHONE_CASING.get());
                        output.accept(ModItems.CAMERA_MODULE.get());
                        output.accept(ModItems.SPEAKER_MODULE.get());
                        output.accept(ModItems.MICROPHONE_MODULE.get());
                        output.accept(ModItems.CHARGING_PORT.get());
                        output.accept(ModItems.BATTERY_CELL.get());
                        output.accept(ModItems.LITHIUM_MINERAL.get());
                        output.accept(ModItems.LITHIUM_CARBONATE.get());
                        output.accept(ModItems.GRAPHITE_ANODE.get());
                        output.accept(ModItems.CATHODE_ACTIVE_MATERIAL.get());
                        output.accept(ModItems.BATTERY_SEPARATOR.get());
                        output.accept(ModItems.BATTERY_ELECTROLYTE.get());
                        output.accept(ModItems.BATTERY_PACK.get());
                        output.accept(ModItems.BLACK_MASS.get());
                        output.accept(ModItems.BATTERY.get());
                        output.accept(ModItems.SMARTPHONE.get());
                        output.accept(ModItems.ELECTRIC_FAN.get());
                        output.accept(ModItems.POWER_ADAPTER.get());
                        output.accept(ModItems.TELEVISION.get());
                        output.accept(ModItems.LAPTOP.get());
                        output.accept(ModItems.WIRELESS_ROUTER.get());
                        output.accept(ModItems.PLASTIC_CONTAINER.get());
                    })
                    .build());
}
