package com.ailudick.capitalismmod.company;

import java.util.Map;

/** Industrial equipment types used by production recipes. Prices are major USD units. */
public enum MachineType {
    NONE("none", 0L, 0L, Map.of()),
    FARM_PLOT("farm_plot", 250L, 1L, Map.of("minecraft:iron_ingot", 2, "minecraft:oak_planks", 4)),
    ORE_PROCESSOR("ore_processor", 500L, 2L, Map.of("minecraft:iron_ingot", 4, "minecraft:copper_ingot", 2, "minecraft:redstone", 1)),
    BLAST_FURNACE("blast_furnace", 1800L, 9L, Map.of("minecraft:iron_ingot", 5, "minecraft:coal", 4, "minecraft:stone", 3)),
    GLASS_FURNACE("glass_furnace", 900L, 3L, Map.of("minecraft:iron_ingot", 4, "minecraft:copper_ingot", 2, "minecraft:glass", 2)),
    WIRE_MILL("wire_mill", 1100L, 3L, Map.of("minecraft:iron_ingot", 4, "minecraft:copper_ingot", 3)),
    LATHE("lathe", 1200L, 4L, Map.of("minecraft:iron_ingot", 5, "minecraft:redstone", 2)),
    MILLING_MACHINE("milling_machine", 1500L, 5L, Map.of("minecraft:iron_ingot", 5, "minecraft:redstone", 2)),
    FOOD_PROCESSOR("food_processor", 1000L, 3L, Map.of("minecraft:iron_ingot", 3, "minecraft:copper_ingot", 2)),
    SAWMILL("sawmill", 1400L, 4L, Map.of("minecraft:iron_ingot", 5,
            "minecraft:copper_ingot", 2, "minecraft:oak_planks", 4)),
    DRY_KILN("dry_kiln", 1800L, 6L, Map.of("minecraft:iron_ingot", 6,
            "minecraft:copper_ingot", 2, "minecraft:glass", 2, "minecraft:coal", 2)),
    OIL_WELL("oil_well", 3500L, 12L, Map.of("capitalismmod:steel_sheet", 4,
            "capitalismmod:machine_frame", 2)),
    OIL_REFINERY("oil_refinery", 4200L, 14L, Map.of("capitalismmod:steel_sheet", 6,
            "capitalismmod:machine_frame", 2, "minecraft:iron_ingot", 4)),
    DISTILLATION_COLUMN("distillation_column", 4600L, 15L, Map.of("capitalismmod:steel_sheet", 8,
            "capitalismmod:machine_frame", 2, "capitalismmod:pressure_pump", 1)),
    VACUUM_DISTILLATION_UNIT("vacuum_distillation_unit", 5200L, 17L, Map.of("capitalismmod:steel_sheet", 8,
            "capitalismmod:machine_frame", 2, "capitalismmod:pressure_pump", 2)),
    CATALYTIC_REFORMER("catalytic_reformer", 5600L, 18L, Map.of("capitalismmod:steel_sheet", 8,
            "capitalismmod:machine_frame", 3, "capitalismmod:industrial_coil", 2)),
    HYDROTREATER("hydrotreater", 5400L, 17L, Map.of("capitalismmod:steel_sheet", 8,
            "capitalismmod:machine_frame", 2, "capitalismmod:pressure_pump", 2)),
    STEAM_REFORMER("steam_reformer", 5000L, 16L, Map.of("capitalismmod:steel_sheet", 7,
            "capitalismmod:machine_frame", 2, "capitalismmod:industrial_coil", 1)),
    CHLOR_ALKALI_CELL("chlor_alkali_cell", 3900L, 11L, Map.of("capitalismmod:steel_sheet", 4,
            "capitalismmod:machine_frame", 1, "capitalismmod:industrial_coil", 2)),
    VINYL_CHLORIDE_UNIT("vinyl_chloride_unit", 4300L, 13L, Map.of("capitalismmod:steel_sheet", 5,
            "capitalismmod:machine_frame", 2, "capitalismmod:pressure_pump", 1)),
    RUBBER_POLYMERIZATION_UNIT("rubber_polymerization_unit", 4100L, 12L, Map.of("capitalismmod:steel_sheet", 5,
            "capitalismmod:machine_frame", 2, "minecraft:glass", 2)),
    METHANOL_SYNTHESIS_UNIT("methanol_synthesis_unit", 4400L, 13L, Map.of("capitalismmod:steel_sheet", 6,
            "capitalismmod:machine_frame", 2, "capitalismmod:pressure_pump", 1, "minecraft:glass", 2)),
    AIR_COMPRESSOR("air_compressor", 2600L, 7L, Map.of("capitalismmod:machine_frame", 2,
            "capitalismmod:electric_motor", 2, "capitalismmod:steel_sheet", 2)),
    CRYOGENIC_AIR_SEPARATION("cryogenic_air_separation", 6200L, 19L, Map.of("capitalismmod:steel_sheet", 8,
            "capitalismmod:machine_frame", 3, "capitalismmod:pressure_pump", 2, "minecraft:glass", 3)),
    FERMENTATION_TANK("fermentation_tank", 2800L, 8L, Map.of("capitalismmod:machine_frame", 2,
            "capitalismmod:steel_sheet", 3, "minecraft:glass", 3)),
    TABLET_PRESS("tablet_press", 3000L, 8L, Map.of("capitalismmod:machine_frame", 2,
            "capitalismmod:steel_sheet", 3, "capitalismmod:electric_motor", 1)),
    STERILE_FILLING_LINE("sterile_filling_line", 4200L, 11L, Map.of("capitalismmod:machine_frame", 2,
            "capitalismmod:steel_sheet", 4, "minecraft:glass", 4)),
    SOLVENT_RECOVERY_UNIT("solvent_recovery_unit", 3000L, 8L, Map.of("capitalismmod:machine_frame", 2,
            "capitalismmod:steel_sheet", 3, "capitalismmod:pressure_pump", 1)),
    PESTICIDE_REACTOR("pesticide_reactor", 3600L, 10L, Map.of("capitalismmod:machine_frame", 2,
            "capitalismmod:steel_sheet", 4, "minecraft:glass", 2, "minecraft:redstone", 2)),
    TIRE_PRESS("tire_press", 3500L, 9L, Map.of("capitalismmod:machine_frame", 2,
            "capitalismmod:steel_sheet", 4, "capitalismmod:electric_motor", 1)),
    ELECTRONIC_CHEMICAL_UNIT("electronic_chemical_unit", 4800L, 13L, Map.of("capitalismmod:machine_frame", 2,
            "capitalismmod:steel_sheet", 4, "minecraft:glass", 3, "minecraft:redstone", 3)),
    PAPER_COATING_LINE("paper_coating_line", 3000L, 8L, Map.of("capitalismmod:machine_frame", 2,
            "capitalismmod:electric_motor", 1, "capitalismmod:steel_sheet", 3)),
    SURFACTANT_REACTOR("surfactant_reactor", 3300L, 9L, Map.of("capitalismmod:machine_frame", 2,
            "capitalismmod:steel_sheet", 3, "minecraft:glass", 3)),
    CARBON_CAPTURE_UNIT("carbon_capture_unit", 5200L, 14L, Map.of("capitalismmod:machine_frame", 2,
            "capitalismmod:steel_sheet", 5, "capitalismmod:pressure_pump", 2)),
    RARE_EARTH_SEPARATION_UNIT("rare_earth_separation_unit", 5800L, 16L, Map.of("capitalismmod:machine_frame", 2,
            "capitalismmod:steel_sheet", 5, "capitalismmod:pressure_pump", 2, "minecraft:glass", 3)),
    URANIUM_MILLING_CIRCUIT("uranium_milling_circuit", 5000L, 14L, Map.of("capitalismmod:machine_frame", 2,
            "capitalismmod:steel_sheet", 4, "capitalismmod:pressure_pump", 1, "minecraft:glass", 2)),
    NUCLEAR_FUEL_FABRICATOR("nuclear_fuel_fabricator", 7600L, 22L, Map.of("capitalismmod:machine_frame", 3,
            "capitalismmod:steel_sheet", 8, "capitalismmod:industrial_coil", 3, "minecraft:glass", 4)),
    RADIATION_SHIELDING_STATION("radiation_shielding_station", 4500L, 12L, Map.of("capitalismmod:machine_frame", 2,
            "capitalismmod:lead_ingot", 4, "capitalismmod:steel_sheet", 3)),
    STEAM_CRACKER("steam_cracker", 3900L, 12L, Map.of("capitalismmod:steel_sheet", 5,
            "capitalismmod:machine_frame", 2, "minecraft:iron_ingot", 4,
            "minecraft:glass", 2)),
    POLYMER_REACTOR("polymer_reactor", 2400L, 7L, Map.of("minecraft:iron_ingot", 6,
            "minecraft:copper_ingot", 3, "minecraft:redstone", 2, "minecraft:glass", 2)),
    BLENDING_UNIT("blending_unit", 2800L, 8L, Map.of("capitalismmod:machine_frame", 2,
            "capitalismmod:steel_sheet", 3, "minecraft:iron_ingot", 4, "minecraft:redstone", 2)),
    INJECTION_MOLDER("injection_molder", 2600L, 7L, Map.of("capitalismmod:machine_frame", 2,
            "capitalismmod:electric_motor", 1, "capitalismmod:steel_sheet", 2)),
    EXTRUSION_LINE("extrusion_line", 3000L, 8L, Map.of("capitalismmod:machine_frame", 2,
            "capitalismmod:electric_motor", 2, "capitalismmod:steel_sheet", 3)),
    PLASTIC_RECYCLER("plastic_recycler", 3400L, 9L, Map.of("capitalismmod:machine_frame", 2,
            "capitalismmod:electric_motor", 2, "capitalismmod:steel_sheet", 3,
            "minecraft:iron_ingot", 4, "minecraft:water_bucket", 1)),
    SILICON_REFINER("silicon_refiner", 4600L, 13L, Map.of("capitalismmod:machine_frame", 2,
            "capitalismmod:steel_sheet", 4, "minecraft:quartz", 2, "minecraft:redstone", 2)),
    CRYSTAL_GROWTH_FURNACE("crystal_growth_furnace", 5000L, 14L, Map.of("capitalismmod:machine_frame", 2,
            "capitalismmod:steel_sheet", 4, "capitalismmod:electric_motor", 1, "minecraft:glass", 2)),
    CHIP_PACKAGING_LINE("chip_packaging_line", 4300L, 11L, Map.of("capitalismmod:machine_frame", 2,
            "capitalismmod:electric_motor", 1, "capitalismmod:copper_wire", 3, "minecraft:glass", 1)),
    SEMICONDUCTOR_FAB("semiconductor_fab", 5200L, 16L, Map.of("capitalismmod:machine_frame", 2,
            "capitalismmod:steel_sheet", 4, "minecraft:quartz", 2, "minecraft:redstone", 3)),
    ELECTRONICS_ASSEMBLY("electronics_assembly", 4200L, 10L, Map.of("capitalismmod:machine_frame", 2,
            "capitalismmod:electric_motor", 1, "capitalismmod:copper_wire", 3, "minecraft:redstone", 3,
            "minecraft:glass", 1)),
    SMT_LINE("smt_line", 4800L, 12L, Map.of("capitalismmod:machine_frame", 2,
            "capitalismmod:electric_motor", 2, "capitalismmod:copper_wire", 4,
            "minecraft:redstone", 4, "minecraft:glass", 2)),
    CHEMICAL_REACTOR("chemical_reactor", 3200L, 9L, Map.of("capitalismmod:machine_frame", 2,
            "capitalismmod:steel_sheet", 3, "minecraft:glass", 2, "minecraft:redstone", 2)),
    LAMINATION_PRESS("lamination_press", 2700L, 7L, Map.of("capitalismmod:machine_frame", 2,
            "capitalismmod:steel_sheet", 3, "minecraft:iron_ingot", 4)),
    ALLOY_FURNACE("alloy_furnace", 2300L, 7L, Map.of("minecraft:iron_ingot", 6,
            "minecraft:coal", 3, "minecraft:redstone", 1)),
    PCB_FABRICATION_LINE("pcb_fabrication_line", 4700L, 12L, Map.of("capitalismmod:machine_frame", 2,
            "capitalismmod:electric_motor", 2, "capitalismmod:copper_wire", 3,
            "minecraft:redstone", 4, "minecraft:glass", 2)),
    PCB_ASSEMBLY_LINE("pcb_assembly_line", 5100L, 13L, Map.of("capitalismmod:machine_frame", 2,
            "capitalismmod:electric_motor", 2, "capitalismmod:copper_wire", 4,
            "minecraft:redstone", 4, "minecraft:glass", 2)),
    WAFER_DICING_SAW("wafer_dicing_saw", 4400L, 11L, Map.of("capitalismmod:machine_frame", 2,
            "capitalismmod:steel_sheet", 3, "minecraft:diamond", 1, "minecraft:redstone", 2)),
    CHIP_TESTING_STATION("chip_testing_station", 4600L, 12L, Map.of("capitalismmod:machine_frame", 2,
            "capitalismmod:copper_wire", 3, "minecraft:redstone", 4, "minecraft:glass", 2)),
    STAMPING_PRESS("stamping_press", 2800L, 8L, Map.of("capitalismmod:machine_frame", 2,
            "capitalismmod:steel_sheet", 4, "minecraft:iron_ingot", 5)),
    MOLDING_COMPOUND_UNIT("molding_compound_unit", 3000L, 8L, Map.of("capitalismmod:machine_frame", 2,
            "capitalismmod:electric_motor", 1, "capitalismmod:steel_sheet", 3)),
    BATTERY_MATERIALS("battery_materials", 3600L, 9L, Map.of("capitalismmod:machine_frame", 2,
            "capitalismmod:steel_sheet", 3, "minecraft:iron_ingot", 4,
            "minecraft:redstone", 2, "minecraft:glass", 2)),
    BATTERY_CELL_LINE("battery_cell_line", 4500L, 11L, Map.of("capitalismmod:machine_frame", 2,
            "capitalismmod:electric_motor", 2, "capitalismmod:copper_wire", 3,
            "capitalismmod:steel_sheet", 3, "minecraft:glass", 2)),
    BATTERY_RECYCLER("battery_recycler", 3800L, 10L, Map.of("capitalismmod:machine_frame", 2,
            "capitalismmod:steel_sheet", 4, "capitalismmod:electric_motor", 1,
            "minecraft:iron_ingot", 4, "minecraft:redstone", 2)),
    ELECTRONICS_RECYCLER("electronics_recycler", 4100L, 11L, Map.of("capitalismmod:machine_frame", 2,
            "capitalismmod:steel_sheet", 4, "capitalismmod:electric_motor", 2,
            "capitalismmod:copper_wire", 2, "minecraft:iron_ingot", 4, "minecraft:redstone", 2)),
    REFURBISHMENT_LINE("refurbishment_line", 3600L, 9L, Map.of("capitalismmod:machine_frame", 2,
            "capitalismmod:electric_motor", 1, "capitalismmod:copper_wire", 2,
            "minecraft:iron_ingot", 4, "minecraft:redstone", 2)),
    CRUSHER("crusher", 1300L, 4L, Map.of("minecraft:iron_ingot", 5, "minecraft:redstone", 2)),
    FLOTATION_CELL("flotation_cell", 2100L, 6L, Map.of("minecraft:iron_ingot", 6, "minecraft:copper_ingot", 3, "minecraft:water_bucket", 2)),
    ELECTRIC_ARC_FURNACE("electric_arc_furnace", 3600L, 12L, Map.of("minecraft:iron_ingot", 8, "minecraft:copper_ingot", 4, "minecraft:redstone", 4)),
    CEMENT_KILN("cement_kiln", 1900L, 6L, Map.of("minecraft:iron_ingot", 6, "minecraft:stone", 8, "minecraft:coal", 3)),
    TEXTILE_MILL("textile_mill", 1700L, 5L, Map.of("minecraft:iron_ingot", 5, "minecraft:copper_ingot", 2, "minecraft:string", 8)),
    PULP_DIGESTER("pulp_digester", 1600L, 5L, Map.of("minecraft:iron_ingot", 5, "minecraft:water_bucket", 2, "minecraft:oak_log", 4)),
    PAPER_MILL("paper_mill", 1800L, 5L, Map.of("minecraft:iron_ingot", 5, "minecraft:copper_ingot", 2)),
    PASTEURIZER("pasteurizer", 1400L, 4L, Map.of("minecraft:iron_ingot", 4, "minecraft:copper_ingot", 2, "minecraft:glass", 2)),
    CANNERY("cannery", 2000L, 6L, Map.of("minecraft:iron_ingot", 5, "minecraft:copper_ingot", 3, "minecraft:glass", 2)),
    FERTILIZER_PLANT("fertilizer_plant", 2800L, 8L, Map.of("minecraft:iron_ingot", 6, "minecraft:quartz", 3, "minecraft:redstone", 2)),
    PHARMACEUTICAL_REACTOR("pharmaceutical_reactor", 3400L, 9L, Map.of("minecraft:iron_ingot", 5, "minecraft:glass", 4, "minecraft:redstone", 3)),
    CNC_MACHINING_CENTER("cnc_machining_center", 3200L, 8L, Map.of("minecraft:iron_ingot", 8, "minecraft:diamond", 1, "minecraft:redstone", 3)),
    ROLLING_MILL("rolling_mill", 2200L, 6L, Map.of("minecraft:iron_ingot", 6, "minecraft:coal", 2)),
    ASSEMBLY_LINE("assembly_line", 3000L, 8L, Map.of("capitalismmod:machine_frame", 2,
            "capitalismmod:electric_motor", 2, "minecraft:glass", 1));

    private final String id;
    private final long purchasePrice;
    private final long maintenancePerCycle;
    private final Map<String, Integer> materials;
    MachineType(String id, long purchasePrice, long maintenancePerCycle, Map<String, Integer> materials) {
        this.id = id;
        this.purchasePrice = purchasePrice;
        this.maintenancePerCycle = maintenancePerCycle;
        this.materials = Map.copyOf(materials);
    }

    public String id() { return id; }
    public long purchasePrice() { return purchasePrice; }
    public long maintenancePerCycle() { return maintenancePerCycle; }
    public Map<String, Integer> materials() { return materials; }
    public static MachineType parse(String id) {
        for (MachineType type : values()) {
            if (type.id.equalsIgnoreCase(id)) return type;
        }
        return null;
    }
}
